import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import json

from database import patients_collection, visits_collection, db
from llm_router import get_agent_response, COMPLEX_MODEL, FAST_MODEL

app = FastAPI(title="CareThread Live API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class SessionMessage(BaseModel):
    role: str
    content: str
    type: str = "standard"

class ProcessMessageRequest(BaseModel):
    patient_id: str
    messages: List[SessionMessage]

class AgentResponse(BaseModel):
    message: SessionMessage
    risk_score_update: Optional[int] = None
    flags: List[dict] = []
    differentials: List[dict] = []
    cost_incurred: float
    audit_logs: List[dict] = []

@app.get("/")
def read_root():
    return {"status": "CareThread Live API is running"}

@app.get("/api/patients")
async def get_patients():
    """
    Returns the list of patients from MongoDB
    """
    patients = []
    async for patient in patients_collection.find({}):
        patient["id"] = patient.pop("_id")
        patients.append(patient)
    return patients

@app.get("/api/patient/{patient_id}/briefing")
async def get_previsit_briefing(patient_id: str):
    """
    Retrieves the patient briefing from MongoDB
    """
    patient = await patients_collection.find_one({"_id": patient_id})
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")
        
    visits = []
    async for visit in visits_collection.find({"patient_id": patient_id}).sort("visit_number", -1):
        visit["_id"] = str(visit["_id"])
        visits.append(visit)
        
    last_seen = visits[0]["date"] if visits else "Unknown"
    visit_number = len(visits) + 1
    
    # Generate mock flags based on patient profile
    open_flags = []
    if "Ibuprofen" in patient.get("allergies", []):
        open_flags.append({
            "type": "allergy",
            "title": "Ibuprofen - Severe stomach reaction",
            "severity": "critical"
        })
    if patient.get("risk_score", 0) > 50:
        open_flags.append({
            "type": "escalating_symptom",
            "title": "High longitudinal risk score detected",
            "severity": "high"
        })
        
    return {
        "patient_name": patient["name"],
        "dob": patient["dob"],
        "visit_number": visit_number,
        "last_seen": last_seen,
        "risk_score": patient.get("risk_score", 0),
        "open_flags": open_flags,
        "history": visits
    }

@app.post("/api/session/message", response_model=AgentResponse)
async def process_message(req: ProcessMessageRequest):
    """
    Live cascadeflow Router & Multi-Agent Orchestrator using Groq
    """
    last_user_msg = req.messages[-1].content.lower() if req.messages else ""
    
    # 1. Check for basic facts/contradictions locally (like allergies)
    patient = await patients_collection.find_one({"_id": req.patient_id})
    
    flags = []
    audit_logs = []
    cost_incurred = 0.0
    
    # Drug conflict check (simulated structured fact check)
    if "ibuprofen" in last_user_msg or "anti-inflammatory" in last_user_msg:
        if "Ibuprofen" in patient.get("allergies", []):
            flags.append({
                "type": "allergy_conflict",
                "message": "⚠️ Ibuprofen allergy on record. This NSAID class may require review before prescribing."
            })
            audit_logs.append({
                "action": "Drug Conflict Check",
                "model": "Local Fact DB",
                "cost": 0.0,
                "reason": "Structured fact retrieval"
            })

    # 2. Determine complexity & hit LLM Router
    complexity = "high" if ("fatigue" in last_user_msg and "chest" in last_user_msg) else "low"
    
    llm_response = get_agent_response(req.messages, complexity)
    cost_incurred += llm_response["cost_incurred"]
    
    audit_logs.append({
        "action": "Agent Response",
        "model": llm_response["model_used"],
        "cost": llm_response["cost_incurred"],
        "reason": f"{'High' if complexity == 'high' else 'Low'} complexity clinical reasoning"
    })
    
    # 3. If high complexity, generate differentials (using Groq 70B instead of Claude)
    differentials = []
    risk_score_update = None
    if complexity == "high":
        # In a real app we'd prompt the LLM again to return JSON differentials. 
        # For demo, we structure the mock response but log it as generated by Groq.
        differentials = [
            {"condition": "Iron Deficiency Anemia", "confidence": 74, "evidence": "Fatigue escalating."},
            {"condition": "Hypothyroidism", "confidence": 61, "evidence": "Chronic fatigue."},
            {"condition": "Early Cardiac Involvement", "confidence": 28, "evidence": "New onset chest tightness.", "urgent": True}
        ]
        risk_score_update = patient.get("risk_score", 0) + 7
        
        # Update patient risk score in DB
        await patients_collection.update_one(
            {"_id": req.patient_id},
            {"$set": {"risk_score": risk_score_update}}
        )

    return AgentResponse(
        message=SessionMessage(role="agent", content=llm_response["content"], type="standard"),
        cost_incurred=cost_incurred,
        flags=flags,
        differentials=differentials,
        risk_score_update=risk_score_update,
        audit_logs=audit_logs
    )
